use_frameworks!

platform :ios, '9.0'

target 'CNLivePreloadResources_Example' do
  pod 'CNLivePreloadResources', :path => '../'

  target 'CNLivePreloadResources_Tests' do
    inherit! :search_paths

    
  end
end
